### ISSUE TITLE
 ReferenceError: tokenRequestUrl is not defined

### ISSUE THREAD

**Issue by etodanik** [2Checkout/node-examples#2]
I get the following error:

```
ReferenceError: tokenRequestUrl is not defined
    at new m (2co.min.js:2)
    at requestToken (2co.min.js:1)
    at tokenRequest (payments.js:36)
```

**Comment by shafeeqsalman** [comment]
What is the reason? How can i overcome this error?

**Comment by 2mhost** [comment]
I randomly get this error!

**Comment by yaroslavOshyyko** [comment]
+1 using Angular 2 with TypeScript

**Comment by craigchristenson** [comment]
Thanks for reporting this issue. The `tokenRequestUrl` is defined when you call `TCO.loadPubKey()`. You can pass in a callback as your second argument to this function to let you know that it has loaded successfully before calling `TCO.requestToken()`.

**Comment by abdullahmw786** [comment]
window.TCO.loadPubKey("", async () => {
   await window.TCO.requestToken(payWithCard, error, data);
  });
